GeekyAnts/nativebase-docs

docs/toast.md

docs: add standalone toast example

---

docs/hidden.md
sidebars.js
src/components/ComponentTheme.js

feat: hidden documentation added

---

docs/darkMode.md

Fixed typo in `docs/darkMode.md` file

Fix typo in darkMode page

---

docs/3.3.x/utility-props.md
docs/next/utility-props.md

Added Rounded to utility props.

fix: added rounded to utility props

---

docs/3.0.x/customizing-theme.md
docs/3.1.x/customizing-theme.md
docs/3.2.x/customizing-theme.md
docs/3.3.x/customizing-theme.md
docs/3.4.x/customizing-theme.md
docs/next/customizing-theme.md

I found a small typo while reading documents. Here is the fix.

Fix typo in document

---

src/components/GettingStartedHero.tsx

Old Content - allowing you to develop apps for Android, iOS and the Web.
New Content - allowing you to develop apps for Android, iOS, and the Web.

Updated Content changes in getting-started

---

docs/3.4.x/responsive.md
docs/next/responsive.md

- https://github.com/GeekyAnts/NativeBase/issues/5268

fix: responsive demo example

---

docs/3.0.x/safe-area-view-props.md
docs/3.1.x/safe-area-view-props.md
docs/3.2.x/safe-area-view-props.md
docs/3.3.x/safe-area-view-props.md
docs/3.4.x/safe-area-view-props.md
docs/next/safe-area-view-props.md

Anchor Text - useSafeAreaInsets
Updated link - https://docs.expo.dev/versions/latest/sdk/safe-area-context/#hooks

Updated link in safe-area-view-props pages 

---

docs/3.0.x/box.md
docs/3.1.x/box.md
docs/3.2.x/box.md
docs/3.3.x/box.md
docs/3.4.x/box.md
docs/next/box.md

Anchor Text - expo-linear-gradient 
Updated Link - https://docs.expo.dev/versions/latest/sdk/linear-gradient/

Updated link in box changes

---

docs/3.4.x/solito.mdx
docs/next/solito.mdx

old content -
For a long long time,
the React Native community has been looking for a way to make Universal Apps a reality with Server Side Rendering support.
Solito is most probably the answer. And as we know, NativeBase already works on all three platforms. This makes the NativeBase and Solito combination a match made in heaven.
new content-
For a long time,
The React Native community had been looking for a way to make Universal Apps a reality with Server Side Rendering support for quite some time.
Solito is the most probable answer. NativeBase already works on all three platforms, as we know, making the NativeBase and Solito combination a match made in heaven.

Update Content Changes in Solito 

---

docs/3.0.x/installation.mdx
docs/3.1.x/installation.mdx
docs/3.2.x/installation.mdx
docs/3.3.x/installation.mdx
docs/3.4.x/installation.mdx
docs/next/installation.mdx

Anchor Text - Refer this guide if you're using Expo
Updated Link - https://docs.expo.dev/guides/using-custom-fonts/

Updated link in customizing-fonts

---

docs/3.0.x/icon-button.md
docs/3.0.x/modal.md
docs/3.1.x/icon-button.md
docs/3.1.x/modal.md
docs/3.2.x/icon-button.md
docs/3.2.x/modal.md
docs/3.3.x/icon-button.md
docs/3.3.x/modal.md
docs/3.4.x/icon-button.md
docs/3.4.x/modal.md
docs/next/icon-button.md
docs/next/modal.md

Anchor Text - button
Updated link - https://www.w3.org/WAI/ARIA/apg/#button

Updated link in icon-button

---

docs/3.0.x/modal.md
docs/3.0.x/radio.md
docs/3.1.x/modal.md
docs/3.1.x/radio.md
docs/3.2.x/modal.md
docs/3.2.x/radio.md
docs/3.3.x/modal.md
docs/3.3.x/radio.md
docs/3.4.x/modal.md
docs/3.4.x/radio.md
docs/next/modal.md
docs/next/radio.md

Anchor Text - Radio Group WAI-ARIA design pattern
Updated link - https://www.w3.org/WAI/ARIA/apg/#radiobutton

Updated link in radio

---

docs/3.0.x/modal.md
docs/3.0.x/popover.md
docs/3.1.x/modal.md
docs/3.1.x/popover.md
docs/3.2.x/modal.md
docs/3.2.x/popover.md
docs/3.3.x/modal.md
docs/3.3.x/popover.md
docs/3.4.x/modal.md
docs/3.4.x/popover.md
docs/next/modal.md
docs/next/popover.md

Anchor text - Dialog WAI-ARIA design pattern
Updated link - https://www.w3.org/WAI/ARIA/apg/#dialog_modal

Updated link in popover

---

docs/3.0.x/link.md
docs/3.0.x/modal.md
docs/3.1.x/link.md
docs/3.1.x/modal.md
docs/3.2.x/link.md
docs/3.2.x/modal.md
docs/3.3.x/link.md
docs/3.3.x/modal.md
docs/3.4.x/link.md
docs/3.4.x/modal.md
docs/next/link.md
docs/next/modal.md

Anchor text - Link WAI-ARIA design pattern
Updated link - https://www.w3.org/WAI/ARIA/apg/#link

Updated link in link

---

docs/3.0.x/modal.md
docs/3.0.x/slider.md
docs/3.1.x/modal.md
docs/3.1.x/slider.md
docs/3.2.x/modal.md
docs/3.2.x/slider.md
docs/3.3.x/modal.md
docs/3.3.x/slider.md
docs/3.4.x/modal.md
docs/3.4.x/slider.md
docs/next/modal.md
docs/next/slider.md

Anchor text - Slider WAI-ARIA design pattern
Updated link - https://www.w3.org/WAI/ARIA/apg/#slidertwothumb

Updated link in slider

---

docs/3.0.x/accessibility.md
docs/3.0.x/modal.md
docs/3.1.x/accessibility.md
docs/3.1.x/modal.md
docs/3.2.x/accessibility.md
docs/3.2.x/modal.md
docs/3.3.x/accessibility.md
docs/3.3.x/modal.md
docs/3.4.x/accessibility.md
docs/3.4.x/modal.md
docs/next/accessibility.md
docs/next/modal.md

Anchor text - WAI-ARIA authoring practices
Updated link - https://www.w3.org/WAI/ARIA/apg/

Updated link in accessibility

---

docs/3.0.x/button.mdx
docs/3.1.x/button.mdx
docs/3.2.x/button.mdx
docs/3.3.x/button.mdx
docs/3.4.x/button.mdx
docs/next/button.mdx

Anchor text - button
Updated link - https://www.w3.org/WAI/ARIA/apg/#button

Updated link in button.mdx

---

docs/3.0.x/checkbox.md
docs/3.0.x/modal.md
docs/3.1.x/checkbox.md
docs/3.1.x/modal.md
docs/3.2.x/checkbox.md
docs/3.2.x/modal.md
docs/3.3.x/checkbox.md
docs/3.3.x/modal.md
docs/3.4.x/checkbox.md
docs/3.4.x/modal.md
docs/next/checkbox.md
docs/next/modal.md

Anchor text - Checkbox WAI-ARIA design pattern
Updated link - https://www.w3.org/WAI/ARIA/apg/#checkbox

Updated link in checkbox

---

docs/3.0.x/alert-dialog.md
docs/3.1.x/alert-dialog.md
docs/3.2.x/alert-dialog.md
docs/3.3.x/alert-dialog.md
docs/3.4.x/alert-dialog.md
docs/next/alert-dialog.md

Anchor text - Alert and Message Dialogs WAI-ARIA design pattern.
Updated link - https://www.w3.org/WAI/ARIA/apg/#alertdialog

Updated link in alert-dialog

---

docs/3.0.x/menu.md
docs/3.1.x/menu.md
docs/3.2.x/menu.md
docs/3.3.x/menu.md
docs/3.4.x/menu.md
docs/next/menu.md

Anchor text - Menu WAI-ARIA design pattern.
Updated link - https://www.w3.org/WAI/ARIA/apg/#menu

Updated link in menu

---

docs/3.0.x/building-footer-tabs.md
docs/3.1.x/building-footer-tabs.md
docs/3.2.x/building-footer-tabs.md
docs/3.3.x/building-footer-tabs.md
docs/3.4.x/building-footer-tabs.md
docs/next/building-footer-tabs.md

deleted content - <Center flex={1} px="3"></Center>

delete center from building-footer

---

docs/3.0.x/utility-first.mdx
docs/3.1.x/utility-first.mdx
docs/3.2.x/utility-first.mdx
docs/3.3.x/utility-first.mdx
docs/3.4.x/utility-first.mdx
docs/next/utility-first.mdx

old Content -
above card
building the card below in React Native.
from productivity boost and saving time there are other benefits by styling components using utility props.
no need to define an object and think about naming them.
new content-
card below
building the following card in React Native.
from productivity boosts and saving time, there are other benefits to styling components using utility props.
no need to define an object and think about naming it.

Updated Content Changes in utility-first

---

docs/3.0.x/design-tokens.md
docs/3.1.x/design-tokens.md
docs/3.2.x/design-tokens.md
docs/3.2.x/utility-props-specificity.md
docs/3.3.x/design-tokens.md
docs/3.3.x/utility-props-specificity.md
docs/3.4.x/design-tokens.md
docs/3.4.x/utility-props-specificity.md
docs/next/design-tokens.md
docs/next/utility-props-specificity.md

Old Content - 
defining a space and color design tokens.
NativeBase follows styled-system's specification to construct design system.
New Content-
defining a space and color design token.
NativeBase follows the  styled-system's specification to construct design systems.

Updated Content Changes in design tokens 

---

docs/3.0.x/design-tokens.md
docs/3.1.x/design-tokens.md
docs/3.2.x/design-tokens.md
docs/3.2.x/pseudo-props-101.md
docs/3.2.x/utility-props-specificity.md
docs/3.3.x/design-tokens.md
docs/3.3.x/pseudo-props-101.md
docs/3.3.x/utility-props-specificity.md
docs/3.4.x/design-tokens.md
docs/3.4.x/pseudo-props-101.md
docs/3.4.x/utility-props-specificity.md
docs/next/design-tokens.md
docs/next/pseudo-props-101.md
docs/next/utility-props-specificity.md

Old Content -
NativeBase has to offer
pass it in _icon
New Content -
NativeBase has to offer,
pass it in _icon,

Updated Content  Changes in pseudo props 101 

---

docs/3.0.x/responsive.md
docs/3.1.x/responsive.md
docs/3.2.x/responsive.md
docs/3.3.x/responsive.md
docs/3.4.x/responsive.md
docs/next/responsive.md

Old Content-
For Example to make a Box width or w responsive
For Example to make a Text fontSize responsive 
New Content-
For example, to make a Box width or w responsive
For example, to make a  Text fontSize responsive

Updated Content Changes in responsive

---

docs/3.0.x/nativebase-factory.md
docs/3.1.x/nativebase-factory.md
docs/3.2.x/nativebase-factory.md
docs/3.3.x/nativebase-factory.md
docs/3.4.x/nativebase-factory.md
docs/next/nativebase-factory.md

Old content -
Original component to be passed on which nativebase props have to be applied.
New content-
Original component to be passed on which NativeBase props have to be applied.

Updated Content Changes in nativebase-factory

---

docs/3.2.x/strict-mode.md
docs/3.3.x/strict-mode.md
docs/3.4.x/strict-mode.md
docs/next/strict-mode.md

old content -
A really handy tool to maintain best practices through out your codebase.
It takes 3 values `error`, `warn` and `off` by default it is set to `warn`. Based on your chosen option it checks for every prop in your project if you have used proper `token values` from theme and you are only passing `string values` to the props and if not then it throws an error or warning or does nothing.
Choosing this mode will throw an error indicating the cause of the error.
new content -
A really handy tool to maintain best practices throughout your codebase.
It takes 3 values - `error`, `warn` and `off`. By default, it is set to `warn`. Based on your chosen option, it checks for every prop in your project. It checks if you have used proper `token values` from the theme and if you are only …

Updated Content Changes in strict-mode

---

docs/3.0.x/customizing-theme.md
docs/3.1.x/customizing-theme.md
docs/3.2.x/customizing-theme.md
docs/3.3.x/customizing-theme.md
docs/3.4.x/customizing-theme.md
docs/next/customizing-theme.md

**Old Content -**
Theme is one core elements of NativeBase.
NativeBase theme is complex object which looks like
It has many other properties but in this recipe, we'll only update few of them
Updated one of the shade of **amber** color.
Finally passed the new **theme** object to the **NativeBaseProvider**.
**New Content -**
The Theme is one of the core elements of NativeBase.
NativeBase theme is a complex object. Here is what it looks like.
It has many other properties but in this recipe, we will update only a few
Updated one of the shades of **amber** color.
Passed the new **theme** object to the **NativeBaseProvider**.

Updated Content Changes in customizing-theme

---

docs/3.0.x/customizing-components.md
docs/3.0.x/customizing-theme.md
docs/3.1.x/customizing-components.md
docs/3.1.x/customizing-theme.md
docs/3.2.x/customizing-components.md
docs/3.2.x/customizing-theme.md
docs/3.3.x/customizing-components.md
docs/3.3.x/customizing-theme.md
docs/3.4.x/customizing-components.md
docs/3.4.x/customizing-theme.md
docs/next/customizing-components.md
docs/next/customizing-theme.md

**Old Content -**
Difference between baseStyle and defaultProps?
outline, solid. You can use it like.
**New Content -**
Difference between baseStyle and defaultProps 
outline, solid.

Updated Content Changes in customizing-components 

---

docs/3.0.x/dark-mode.md
docs/3.1.x/dark-mode.md
docs/3.2.x/dark-mode.md
docs/3.3.x/dark-mode.md
docs/3.4.x/dark-mode.md
docs/next/dark-mode.md

Old Content -
Making components dark mode compatible
There are 2 way to achieve this:
New Content -
Making Components Dark Mode Compatible
There are 2 ways to achieve this:

Updated Content Changes in dark-mode

---

docs/3.0.x/theme.md
docs/3.1.x/theme.md
docs/3.2.x/theme.md
docs/3.3.x/theme.md
docs/3.4.x/theme.md
docs/next/theme.md

**old content -**
First tool is useTheme which you can use to access the values from the current theme.
contrasting color to the text then
change the color mode then you can try
**New Content -**
The first tool is useTheme which you can use to access the values from the current theme.
contrasting color to the text,
change the color mode, then you can try

Updated Content Changes in theme

---

docs/3.0.x/center.md
docs/3.1.x/center.md
docs/3.2.x/center.md
docs/3.3.x/center.md
docs/3.4.x/center.md
docs/next/center.md

Old Content -
Square and Circle automatically centers their children.
New Content - 
Square and Circle automatically center their children.

Updated Content Changes in center

---

docs/3.0.x/flex.md
docs/3.1.x/flex.md
docs/3.2.x/flex.md
docs/3.3.x/flex.md
docs/3.4.x/flex.md
docs/next/flex.md

Old Content -
Flex components comes with some helpful shorthand props:
New Content -
Flex components come with some helpful shorthand props:

Updated Content Changes in flex

---

docs/3.0.x/flex.md
docs/3.1.x/flex.md
docs/3.2.x/button.mdx
docs/3.2.x/flex.md
docs/3.3.x/button.mdx
docs/3.3.x/flex.md
docs/3.4.x/button.mdx
docs/3.4.x/flex.md
docs/next/button.mdx
docs/next/flex.md

**Old Content -** 
Flush the buttons together by removing the border radius of the its children as needed.
**New Content -** 
Flush the buttons together by removing the border radius of its children as needed.

Updated  Content Changes in button

---

docs/3.0.x/icon-button.md
docs/3.1.x/icon-button.md
docs/3.2.x/icon-button.md
docs/3.3.x/icon-button.md
docs/3.4.x/icon-button.md
docs/next/icon-button.md

**Old Content -**
IconButton composes the Button component.
**New Content -** 
IconButton consists of the Button component.

Update Content Changes in icon-button

---

docs/3.0.x/slider.md
docs/3.1.x/slider.md
docs/3.2.x/slider.md
docs/3.3.x/slider.md
docs/3.4.x/slider.md
docs/next/slider.md

**Old Content -**
The handle that's used to change the slider value.
**New Content -**
The handle that is used to change the slider value.

Updated Content Changes in slider

---

src/components/ComponentTheme.tsx

**Old Content -** 
Checkout the default theme 
**New Content -** 
Check out the default theme

Updated Content Changes  in ComponentTheme 

---

docs/3.0.x/accessibility.md
docs/3.1.x/accessibility.md
docs/3.2.x/accessibility.md
docs/3.3.x/accessibility.md
docs/3.4.x/accessibility.md
docs/next/accessibility.md

Old Content -
NativeBase comes with the latest accessibility standards out of the box including aria and role attributes, focus management, and keyboard navigation.
NativeBase uses React Native ARIA to implements
In many NativeBase Components, we move focus based on the interactions a user normally takes in a given component.
New Content -
NativeBase comes with the latest accessibility standards out of the box including React Native ARIA and role attributes, focus management, and keyboard navigation.
NativeBase uses React Native to implement 
In many NativeBase Components, we move focus, based on the interactions a user normally makes in a given component.

Updated Content Changes in accessibility

---

docs/3.2.x/image.md
docs/3.3.x/image.md
docs/3.4.x/image.md
docs/next/image.md

Old Content - 
When using require statement from next for image keep this in mind.
New Content - 
When using require statement from next for image, keep this in mind.

 Updated Content Changes in image

---

docs/3.0.x/modal.md
docs/3.1.x/modal.md
docs/3.2.x/modal.md
docs/3.3.x/modal.md
docs/3.3.x/popover.md
docs/3.4.x/modal.md
docs/3.4.x/popover.md
docs/next/modal.md
docs/next/popover.md

Old Content - 
It is a non-modal dialog and used to provide contextual information to the user.
New Content - 
It is a non-modal dialog used to provide contextual information to the user.

Updated Content Changes in popover 

---

docs/3.0.x/modal.md
docs/3.1.x/modal.md
docs/3.2.x/modal.md
docs/3.3.x/modal.md
docs/3.4.x/modal.md
docs/next/modal.md

Old Content - 
NativeBase export a Modal Compound component:
New Content -
NativeBase exports a Modal Compound component:

Updated Content Changes in Modal

---

docs/3.0.x/changelog.md
docs/3.1.x/changelog.md
docs/3.2.x/changelog.md
docs/3.3.x/changelog.md
docs/3.4.x/changelog.md
docs/next/changelog.md

Old Content - 
For more details. Visit
New Content -
For more details, visit

Updated Content Changes in changelog

---

docs/3.0.x/migration/v3.md
docs/3.1.x/migration/v3.md
docs/3.2.x/migration/v3.md
docs/3.3.x/migration/v3.md
docs/3.4.x/migration/v3.md
docs/next/migration/v3.md

Old Content - 
you might face a lot of changes from v2 to v3.
This might be a bit of tedious work but we promise you, it will be worth it!
all the expectations set by it's predecessor and makes the overall
New Content -
you might come across a lot of changes while upgrading from v2 to v3.
This might seem to be a bit of tedious work but we promise you, it will be worth it!
all the expectations set by its predecessor and makes the overall

Updated Content Changes in v3

---

docs/3.0.x/use-contrast-text.md
docs/3.1.x/use-contrast-text.md
docs/3.2.x/use-contrast-text.md
docs/3.3.x/use-contrast-text.md
docs/3.4.x/use-contrast-text.md
docs/next/use-contrast-text.md

Old Content -
provides contrasting color based on its theme.
You can also choose to get color with
New Content -
provides contrasting colors based on its theme.
You can also choose to get colors with

Updated  Content Changes in use-contrast-text

---

docs/3.3.x/use-media-query.md
docs/3.4.x/use-media-query.md
docs/next/use-media-query.md

Old Content -
useMediaQuery is a custom hook that helps detect matches between between a 
New Content -
useMediaQuery is a custom hook that helps detect matches between

Updated Content Changes in use-media-query

---

docs/3.3.x/use-disclose.md
docs/3.4.x/use-disclose.md
docs/next/use-disclose.md

Old Content -
common open, close, or toggle scenarios and can control feedback component such as
New Content -
common open, close, or toggle scenarios and can control feedback components such as

Updated Content Changes in use-disclose

---

docs/3.0.x/icon.md
docs/3.1.x/icon.md
docs/3.2.x/icon.md
docs/3.3.x/icon.md
docs/3.4.x/icon.md
docs/next/icon.md

**Old Content:**
multiples ways. They are listed below:
We provides a set of commonly used interface icons. So you can directly use them in your project.
Create icon by creating an SVG Icon
Create icon using createIcon function and use it as a component
New Content :
**multiples ways:**
We provide a set of commonly used interface icons which you can directly use in your project.
Create icon by creating an SVG Icon.
Create icon using createIcon function and use it as a component.

Updated Content Changes in icon

---

docs/3.0.x/building-drawer-navigation.md
docs/3.1.x/building-drawer-navigation.md
docs/3.2.x/building-drawer-navigation.md
docs/3.3.x/building-drawer-navigation.md
docs/3.4.x/building-drawer-navigation.md
docs/next/building-drawer-navigation.md

- fix: drawer navigation https://github.com/GeekyAnts/NativeBase/issues/5506

fix: drawer navigation
